### ISSUE TITLE
Option to hide error when not in production

### ISSUE THREAD

**Issue by OmgImAlexis** [lsentkiewicz/express-api-error-handler#1]
With 5XX errors quite a bit of information can be leaked just by the error message so it'd be nice to have it reply with a generic 500 error in certain cases.

For example this still shows too much info.

```json
{
    "status": 500,
    "error": "Cannot read property 'tokenSet' of undefined"
}
```

**Comment by lstkz** [comment]
Added `hideProdErrors` option.
See readme.

Thanks for reporting it.
